### PR TITLE
fix(whitelist): add dl.k8s.io to proxy whitelist

### PR DESCRIPTION
**Pull request by frickjack**
added dl.k8s.io to proxy whitelist - k8s is not posting downloads to this domain:

https://github.com/kubernetes/kubernetes/issues/33726
https://github.com/kubernetes/kubernetes/releases

### CODE REVIEW

**Comment by philloooo** [comment]
I thought the whitelist is not used for the transparent proxy? @kyleaschmitt  ?

**Comment by frickjack** [comment]
wget dl.k8s.io from the k8s provisioner was blocked before I added it to the squid whitelist ...

**Comment by frickjack** [comment]
Cool - just pushed a patch to setup the .k8s.io whitelist wildcard - time to merge? :-)

**Comment by kyleaschmitt** [comment]
:+1:

**Comment by kyleaschmitt** [comment]
@philloooo https is transparent.  So, if they bother to encrypt, it gets a free pass, otherwise, must be whitelisted.

**Pull request merged**
